language: php
php:
  - 7.4

install:
  - pecl install pcov
  - composer install

script:
  - composer cs
  - composer analyse
  - composer coverage

after_success:
    - bash <(curl -s https://codecov.io/bash)