language: php
php:
  - 7.4

before_install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
  - nvm install --lts

install:
  - pecl install pcov
  - composer install --no-scripts

jobs:
  include:
    - stage: test
      script:
        - composer cs
        - composer analyse
        - composer coverage
    - stage: deploy
      script:
        - composer install --no-dev --no-scripts
        - npx serverless deploy

stages:
  - test
  - name: deploy
    if: (branch = main) AND (NOT (type IN (pull_request)))

after_success:
    - bash <(curl -s https://codecov.io/bash)
