language: php
php:
  - 7.4

before_install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
  - nvm install --lts

install:
  - pecl install pcov
  - composer install

script:
  - composer cs
  - composer analyse
  - composer coverage
  - composer install --no-dev

after_success:
    - bash <(curl -s https://codecov.io/bash)
