language: php
php:
  - 7.4
dist: xenial
os: linux

before_install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
  - nvm install --lts

jobs:
  include:
    - stage: test
      script:
        - pecl install pcov
        - composer install --no-scripts
        - composer cs
        - composer analyse
        - composer coverage
    - stage: deploy
      script:
        - composer install --no-dev --no-scripts
        - npx serverless deploy

stages:
  - test
  - name: deploy
    if: (branch = main) AND (NOT (type IN (pull_request)))

after_success:
    - test $TRAVIS_BRANCH = "main" &&
      test $TRAVIS_PULL_REQUEST = "false" &&
      bash <(curl -s https://codecov.io/bash)
