service: portfolio-backend

variablesResolutionMode: null
configValidationMode: error

disabledDeprecations:
    - NEW_VARIABLES_RESOLVER # Disabled because of bref

provider:
    name: aws
    region: eu-west-2
    runtime: provided.al2
    lambdaHashingVersion: 20201221
    iam:
        deploymentRole: ${ssm(eu-west-2):portfolio-backend-cfnRole}
        role: ${ssm(eu-west-2):portfolio-backend-lambdaRole}
    deploymentBucket:
        name: ${ssm(eu-west-2):serverless-deploy-bucket}

plugins:
    - ./vendor/bref/bref

# Exclude files from deployment
package:
  patterns:
    - '!node_modules/**'
    - '!tests/**'
    - '!terraform/**'

functions:
  api:
    handler: public/index.php
    description: ''
    timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
    environment:
      CACHE_DRIVER: tmp
      LOG_CHANNEL: errorlog
      DYNAMODB_EMAIL_TABLE_NAME: portfolio-backend-emails
    layers:
      - ${bref:layer.php-74-fpm}
    events:
      -   httpApi: '*'

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: portfolio-backend-emails
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
